server:
  port: 9999

spring:
  application:
    name: LAIGOU-ZUUL

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://root:xf1234@localhost:8761/eureka/

zuul:
  ignoredServices: '*' #只能通过路由访问，不能使用服务名访问
  routes:
    plat:
      serviceId: AIGOU-PLAT
      path: /plat/**
  prefix: /services