server:
  port: 6969

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/xiongfeng96119/git-demo.git
  application:
    name: LAIGOU-CONFIG

#将配置中心服务端注册到Eureka注册中心中
eureka:
  client:
    serviceUrl:
      defaultZone: http://root:xf1234@localhost:8761/eureka/ #注册中心的地址
  instance:
    prefer-ip-address: true

